"""empty message

Revision ID: d345e1cac250
Revises: 6d566a686839
Create Date: 2023-05-01 14:31:46.912865

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd345e1cac250'
down_revision = '6d566a686839'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Purchase', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'Purchase', 'Project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Purchase', type_='foreignkey')
    op.drop_column('Purchase', 'project_id')
    # ### end Alembic commands ###
