"""empty message

Revision ID: eb212761aab6
Revises: 349e5aa6e3a2
Create Date: 2023-05-03 15:47:52.672570

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'eb212761aab6'
down_revision = '349e5aa6e3a2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'first_name', nullable=False, new_column_name='name')
    op.drop_column('User', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
