"""empty message

Revision ID: eacbe02c9967
Revises: 13d2068684ab
Create Date: 2023-04-25 17:27:57.413391

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'eacbe02c9967'
down_revision = '13d2068684ab'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('login_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('User', sa.Column('kakao_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'kakao_id')
    op.drop_column('User', 'login_type')
    # ### end Alembic commands ###
