"""empty message

Revision ID: 7fb86160e2b6
Revises: d40038d9ac17
Create Date: 2023-04-28 02:59:33.144018

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7fb86160e2b6'
down_revision = 'd40038d9ac17'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Purchase', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('Purchase', sa.Column('product_image_list', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'Purchase', 'User', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Purchase', type_='foreignkey')
    op.drop_column('Purchase', 'product_image_list')
    op.drop_column('Purchase', 'created_by_id')
    # ### end Alembic commands ###
